image: node:5.0.0-slim
git:
  path: github.com/vjscjp304/voteui24
script:
  - echo "build commands"
  - echo "no build command"
  - echo "no test command"
clone:
  path: github.com/vjscjp304/voteui24
build:
  image: node:5.0.0-slim
  commands:
    - echo "build commands"
    - echo "no build command"
    - echo "no test command"
publish:
  docker:
    file: ./Dockerfile
    insecure: true
    username: $$docker_user
    password: $$docker_key
    registry: $$docker_registry
    repo: $$docker_repo
    email: $$docker_user_email
    tag: $$COMMIT
    
